import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";

export async function POST(request: Request) {
  const { input, output } = await request.json();

  const doc = new jsPDF();
  doc.setFontSize(20);
  doc.setTextColor(0, 43, 73);
  doc.text("GRIDMIND EPC™ AUTOMATED ENGINEERING BID", 14, 22);

  doc.setFontSize(11);
  doc.setTextColor(35, 35, 35);
  doc.text(`Asset Key: ${input.projectName}`, 14, 36);
  doc.text(`System Configuration Capacity: ${Number(input.capacityMwp).toFixed(2)} MWp Utility Scale`, 14, 44);

  doc.setFontSize(14);
  doc.setTextColor(255, 140, 0);
  doc.text("1. Infrastructure Optimization Summary", 14, 60);

  const lines = [
    ["Main Substation Step-Up Transformer", `${output.transformerMva} MVA Capacity Unit`],
    ["Underground MV Collection Cables", `${output.conductorSizeMm2} mm² Cross-Section (Al)`],
    ["Estimated Cable Losses", `${Number(output.lossPct).toFixed(2)}%`],
    ["Gross Project EPC CAPEX Evaluation", `$${Number(output.totalCostUsd).toLocaleString()} USD`]
  ];

  let y = 75;
  for (const [label, value] of lines) {
    doc.setFontSize(10);
    doc.setTextColor(35, 35, 35);
    doc.text(label, 14, y);
    doc.setTextColor(0, 43, 73);
    doc.text(value, 110, y);
    y += 10;
  }

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by GridMind EPC™. Final values require engineering and grid-code review.", 14, 278);

  const pdf = Buffer.from(doc.output("arraybuffer"));

  return new NextResponse(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": "attachment; filename=GridMind_Proposal.pdf"
    }
  });
}
